language: cpp

cache: ccache

notifications:
  email:
    on_success: never
    on_failure: always

jobs:
 include:
  - os: linux
    dist: bionic
    compiler: gcc
    env:
     - QT_BASE=48
#  - os: linux
#    dist: trusty
#    compiler: gcc
#    env:
#     - QT_BASE=55
#  - os: linux
#    dist: trusty
#    compiler: gcc
#    env:
#     - QT_BASE=56
#  - os: linux
#    dist: xenial
#    compiler: gcc
#    env:
#     - QT_BASE=57
#  - os: linux
#    dist: xenial
#    compiler: gcc
#    env:
#     - QT_BASE=58
#  - os: linux
#    dist: xenial
#    compiler: gcc
#    env:
#     - QT_BASE=59
#  - os: linux
#    dist: xenial
#    compiler: gcc
#    env:
#     - QT_BASE=510
#  - os: linux
#    dist: bionic
#    compiler: gcc
#    env:
#     - QT_BASE=511
  - os: linux
    dist: focal
    compiler: gcc
    env:
     - QT_BASE=512
#  - os: linux
#    dist: bionic
#    compiler: gcc
#    env:
#     - QT_BASE=513
  - os: linux
    dist: focal
    compiler: gcc
    env:
     - QT_BASE=514
  - os: linux
    dist: focal
    compiler: gcc
    env:
     - QT_BASE=515
  - os: linux
    dist: bionic
    compiler: gcc
    env:
     - JOB="Ubuntu packaging test"
  - os: linux
    dist: focal
    services: docker
    env:
     - DOCKER="fedora_33"
#  - os: osx
#    compiler: clang
#    osx_image: xcode12
  - os: osx
    compiler: clang
    osx_image: xcode12.2
  - os: windows
    env:
     - JOB="Visual Studio 2017 Build Tools"
     - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
  - os: freebsd

before_install:
# - if [[ "$QT_BASE" = "48"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt487-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "51"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt511-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "52"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt521-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "53"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt532-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "54"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt542-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "55"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt551-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "56"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt563-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "57"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt571-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "58"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt58-$TRAVIS_DIST  -y; fi
  - if [[ "$QT_BASE" = "59"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt597-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "510" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "511" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.11.3-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "512" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.12.10-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "513" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.13.2-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "514" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.14.2-$TRAVIS_DIST -y; fi
  - if [[ "$QT_BASE" = "515" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-$TRAVIS_DIST -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
      sudo apt-get update -qq;
    fi

install:
  - if [[ "$QT_BASE" = ""    && "$TRAVIS_OS_NAME" = "linux" && "$DOCKER" = "" ]]; then sudo apt-get install -qq lintian kdelibs5-dev debhelper cmake libosmesa6-dev libtinyxml-dev fakeroot qt5-qmake qtbase5-dev libqt4-opengl-dev libqt5opengl5-dev; fi
  - if [[ "$QT_BASE" = "48"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq libqt4-dev libqt4-opengl-dev ; fi
  - if [[ "$QT_BASE" = "51"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  - if [[ "$QT_BASE" = "52"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  - if [[ "$QT_BASE" = "53"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  - if [[ "$QT_BASE" = "54"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  - if [[ "$QT_BASE" = "55"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  - if [[ "$QT_BASE" = "56"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  - if [[ "$QT_BASE" = "57"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  - if [[ "$QT_BASE" = "58"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi 
  - if [[ "$QT_BASE" = "59"  && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi 
  - if [[ "$QT_BASE" = "510" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi 
  - if [[ "$QT_BASE" = "511" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  - if [[ "$QT_BASE" = "512" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  - if [[ "$QT_BASE" = "513" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  - if [[ "$QT_BASE" = "514" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  - if [[ "$QT_BASE" = "515" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "freebsd" ]; then sudo pkg install -y qt5-gui qt5-opengl qt5-linguist qt5-widgets qt5-buildtools qt5-qmake gl2ps tinyxml gmake libosmesa mesa-devel lib3ds desktop-file-utils shared-mime-info ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
      sudo apt-get install -qq libglu1-mesa-dev libosmesa6-dev libgl2ps-dev libtinyxml-dev;
      if [[ "$QT_BASE" = "" && "$DOCKER" = "" ]] ; then
        sudo apt-get install -qq extra-cmake-modules libkf5kio-dev libkf5kdelibs4support5-bin || true;
      fi
    fi
  
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      cd QT;
      if  [ -n "$QT_BASE" ] ; then
        qmake DEFINES+=USE_CPP11 -spec linux-g++-64;
        make;
      else
        if [ "$DOCKER" = "" ] ;then
          sed -i 's/libkf5kio-dev//g' debian/control ;
          sed -i 's/extra-cmake-modules//g' debian/control ;
          sed -i 's/libkf5kdelibs4support5-bin//g' debian/control ;
          ./makedeb;
        fi;
        if [ -n "$DOCKER" ] ;then
          cd docker ;
          if [ -n "$DOCKER_USERNAME" ] ; then docker logout ; echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ; fi ;
          docker build -t ldview-$DOCKER -f Dockerfile-$DOCKER . ;
          docker run ldview-$DOCKER ;
        fi;
      fi
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      cd MacOSX/LDView;
      xcodebuild;
    fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      export PATH=$MSBUILD_PATH:$PATH;
      msbuild.exe LDView.vcxproj;
    fi
  - if [ "$TRAVIS_OS_NAME" = "freebsd" ]; then
      cd QT;
      sudo ./freebsd.sh;
    fi
